/*
 * 경매 출품 조회 성능 개선 원칙
 * 1. CAU_ENTRY와 검색 필수 테이블만으로 대상 키를 먼저 페이징
 * 2. 부가 테이블·코드명·고비용 계산은 페이징된 건에만 조인
 * 3. 날짜는 시작 이상, 종료일 + 1 미만 조건 사용
 *
 * 실제 SELECT 컬럼과 업무 조건은 원본 매퍼에서 옮겨야 합니다.
 */
WITH PAGE_KEY AS (
	SELECT	V_ENTRYCD
		,	ROW_NUMBER() OVER (ORDER BY V_ENTRYCD DESC) AS RN
	FROM	CAU_ENTRY
	WHERE	1 = 1
	AND		(:DATE_S IS NULL OR D_REG_DTM >= TO_DATE(:DATE_S, 'YYYYMMDD'))
	AND		(:DATE_E IS NULL OR D_REG_DTM < TO_DATE(:DATE_E, 'YYYYMMDD') + 1)
),
PAGE_ENTRY AS (
	SELECT	V_ENTRYCD
	FROM	PAGE_KEY
	WHERE	RN BETWEEN :START_RN AND :END_RN
)
SELECT	CER.V_ENTRYCD
	,	CCI.V_CARCD
	,	CCI.V_CARNO
FROM	PAGE_ENTRY P
JOIN	CAU_ENTRY CER
	ON	CER.V_ENTRYCD = P.V_ENTRYCD
LEFT JOIN CAU_CAR_INFO CCI
	ON	CCI.V_ENTRYCD = CER.V_ENTRYCD
ORDER BY CER.V_ENTRYCD DESC;
